#if !canImport(ObjectiveC)
import XCTest

extension ColumnTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ColumnTests = [
        ("testDescription", testDescription),
    ]
}

extension ConnectionTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ConnectionTests = [
        ("testInitWithInvalidURL", testInitWithInvalidURL),
        ("testInitWithoutURL", testInitWithoutURL),
        ("testInitWithURL", testInitWithURL),
    ]
}

extension ErrorTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ErrorTests = [
        ("testDescription", testDescription),
    ]
}

extension ExecTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__ExecTests = [
        ("testExec", testExec),
        ("testExecAbort", testExecAbort),
        ("testFalsePragma", testFalsePragma),
        ("testPragmas", testPragmas),
        ("testThrowing", testThrowing),
        ("testVersion", testVersion),
    ]
}

extension QueryTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__QueryTests = [
        ("testQuery", testQuery),
    ]
}

extension SerialTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__SerialTests = [
        ("testExample", testExample),
    ]
}

extension UpdateTests {
    // DO NOT MODIFY: This is autogenerated, use:
    //   `swift test --generate-linuxmain`
    // to regenerate.
    static let __allTests__UpdateTests = [
        ("testTransaction", testTransaction),
        ("testTypes", testTypes),
        ("testUpdateFail", testUpdateFail),
    ]
}

public func __allTests() -> [XCTestCaseEntry] {
    return [
        testCase(ColumnTests.__allTests__ColumnTests),
        testCase(ConnectionTests.__allTests__ConnectionTests),
        testCase(ErrorTests.__allTests__ErrorTests),
        testCase(ExecTests.__allTests__ExecTests),
        testCase(QueryTests.__allTests__QueryTests),
        testCase(SerialTests.__allTests__SerialTests),
        testCase(UpdateTests.__allTests__UpdateTests),
    ]
}
#endif
